name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12' # Use Node.js version 12

    - name: Install dependencies
      run: npm install

    - name: Update Browserslist DB
      run: npx browserslist@latest --update-db

    - name: Fix color-adjust warning
      run: |
        find ./node_modules -type f -name "*.css" -exec sed -i 's/color-adjust/print-color-adjust/g' {} +

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Build the project
      run: CI=false npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
